### ISSUE TITLE
Syntax for update?

### ISSUE THREAD

**Issue by richcorbs** [searchableguy/actdb#1]
It looks like `update` is a supported op but I can't figure out the syntax. Could I get a sample please?

**Comment by richcorbs** [comment]
And also for `delete`?

**Comment by searchableguy** [comment]
@richcorbs check
https://github.com/searchableguy/actdb/blob/master/examples/server.ts for those. I am going to introduce some changes in the next few days to make it more robust after which everything will be documented.

**Comment by richcorbs** [comment]
Cool! And thanks for the response.

I'm trying to use delete following the pattern there and cannot get it to work:

```
const body = { deletes: [ { id: 234 } ] };

body.deletes.forEach(async (d) => {
    let removed = await records.remove(d)
    console.log('removed', removed)
})
```
There are no errors, `id` is a number, the record with `id === 123` exists, `removed` is undefined, and the record isn't removed. I'm sure I'm missing something.

**Comment by searchableguy** [comment]
That should work. Can you show me your record type?

And have you cleared the cache since the last run, there are new changes. 

I don't know which OS you are on but on Linux, you can run `rm -rf ~/.cache/deno` and start your app with `deno run -A app.ts`. Let me know if this works.

**Comment by richcorbs** [comment]
Hmmm, I don't know typescript (yet) and was trying to use this without types. Could that be my problem?

**Comment by searchableguy** [comment]
No. That shouldn't cause any problem. Did you delete the cache and re-run?

**Comment by richcorbs** [comment]
Took me a bit to find the cache on OSX but I found and deleted it.

Running `deno run -A app.js` gave me this error:

```
$ deno run -A app.js
I[2020-05-27T20:29:17.746Z] servest:router listening on :3100
http://localhost:3100/
error: Uncaught TypeError: Cannot read property 'records' of undefined
    if (!tree.stores[name]) {
                    ^
    at FileAdapter.createStore (https://deno.land/x/actdb/adapters/FileAdapter.ts:101:21)
```

**Comment by searchableguy** [comment]
hm Is it possible to see app.js ?

**Comment by richcorbs** [comment]
Sorry for taking so much of your time. I appreciate it. I deleted the db file and started over. Everything is working.

The only weird thing I'm seeing is that after an `update` or `delete` and then a `records.get()` the record isn't yet deleted/updated and the get returns the original unchanged records list.

Maybe that's not a valid use case. I can get the deleted/updated record from the result of the operation.

**Comment by searchableguy** [comment]
That's pretty odd. I can't reproduce it from my side. If you can just show me the app.js, I might be able to figure out.

**Comment by richcorbs** [comment]
Here it is. It's ugly. I'm still learning.

```
import { createApp, } from "https://servestjs.org/@v1.1.0/mod.ts";
import { Act, FileAdapter, Store } from 'https://deno.land/x/actdb/mod.ts';
import { v4 } from 'https://deno.land/std/uuid/mod.ts';

const app = createApp();

const db = new Act(new FileAdapter("myql.json"))
const users = db.createStore("users")
const records = db.createStore("records")

app.post("/authenticate", async (req) => {
  const body = await req.json();
  console.log('body', body)
  let response = { token: null }
  if (body.username && body.password) {
    let [user] = await users.get({ username: body.username })
    console.log('user', user)
    if (user && user?.password === body.password) {
      response = { token: user.id }
    } else if (!user) {
      console.log('INSERT')
      await users.insert([{ id: v4.generate(), username: body.username, password: body.password }])
      user = await users.get({ username: body.username })
      console.log('user', user)
      response = { token: user.id }
    }
  }
  console.log('response', response)
  req.respond({
    status: 200,
    headers: new Headers({
      'content-type': 'application/json',
    }),
    body: JSON.stringify(response),
  });
});

app.post("/myql", async (req) => {
  let token = await req.headers.get("Authorization")?.replace("Bearer ", "")
  console.log('token', token)
  const user = users.get({ id: token })
  let body = {}
  let results = []
  if (user) {
    body = await req.json();
    console.log('body', body)
    switch (body.op) {
      case "create":
        console.log("CREATE")
        if (body.creates && body.creates.length > 0) {
          body.creates.forEach(async (c) => {
            c.id = v4.generate()
            console.log('creating', c.id)
            await records.insert([c])
          })
        }
        results = await records.get()
        break
      case "read":
        console.log("READ")
        let tempResults = []
        for (let read of body.reads) {
          tempResults = await records.get(read?.filter)
          console.log('tempResults', tempResults);
          if (read.fields && read.fields.length > 0) {
            tempResults.forEach((r) => {
              Object.keys(r).forEach((k) => {
                if (!read.fields.includes(k)) delete r[k]
              })
            })
          }
          results.push(tempResults)
        }
        break
      case "update":
        console.log("UPDATE")
        if (body.updates && body.updates.length > 0) {
          body.updates.forEach(async (u) => {
            const [record] = await records.update(u.filter, u.data)
            console.log('record after update', record)
          })
        }
        results = await records.get()
        break
      case "delete":
        console.log("DELETE")
        if (body.deletes && body.deletes.length > 0) {
          body.deletes.forEach(async (d) => {
            let removed = await records.remove(d)
            console.log('removed', removed)
          })
        }
        results = await records.get()
        break
      default:
        console.log("DEFAULT")
        break
    }
  }
  console.log('body', results)
  req.respond({
    status: 200,
    headers: new Headers({
      'content-type': 'application/json',
    }),
    body: JSON.stringify(results),
  });
});

app.listen({ port: 3100 })
console.log("http://localhost:3100/");
```

**Comment by richcorbs** [comment]
1. POST to /authenticate with { username: 'me', password: 'password' }.
2. This will generate a user record and return the user.id as a token.
3. Copy the user.id/token.
4. Use the token in an Authorization header "Bearer <token>".
5. Create some things by POST to /myql with the Authorization header.
```
{
	"op": "create",
	"creates": [
		{ "thing": "abc" },
		{ "thing": "def" }
	]
}
```
6. Delete some things by POST to /myql with the Authorization header.
```
{
	"op": "delete",
	"deletes": [
		{ "thing": "def" }
	]
}
```

**Comment by searchableguy** [comment]
Any reason for not following rest?
I can see serverjs provide a router - https://servestjs.org/use-router
Your code would be better organized and API easier to consume.

**Comment by richcorbs** [comment]
I know its crazy but I'm experimenting with making a "typeless, dynamic graphql" API.

My idea is to create an API that will:

- allow the user to upload any JSON
- have it be queryable by any field
- have it return only the fields they ask for

Essentially I wanted dynamic graphql based on the user's data and couldn't find a way to do that.

**Comment by richcorbs** [comment]
Since I'm just playing I didn't want to go all in on postgres or something like that right away.

**Comment by searchableguy** [comment]
Interesting use case. I have been working on something similar. What is this for if I am not prying too much?

**Comment by richcorbs** [comment]
It's mainly for fun and an excuse to play with Deno. I learn best when I have a purpose or a project to work on. I chose this "project" because I'm always looking for tools to speed up backend dev with enough power to be useful but simple enough not to get in the way.

Maybe some other dev would find it useful too if I get that far.

**Comment by searchableguy** [comment]
If you don't mind, would you like to connect about this? 
I am solving the same problem but on a bigger scale right now.
Shoot me an email at me@searchableguy.com if you do.
